services:
  service-registry:
    container_name: serviceregistry
    build: service-registry/.
    ports:
      - "8761:8761"
    networks:
      - microservicesnet
  api-gateway:
    container_name: apigateway
    build: api-gateway/.
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=serviceregistry
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - products-service
      - carts-service
    networks:
      - microservicesnet
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservicesnet
  products-service:
    container_name: productsservice
    build: products-service/.
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=serviceregistry
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - kafka
    networks:
      - microservicesnet
  carts-service:
    container_name: cartsservice
    build: carts-service/.
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=serviceregistry
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - kafka
    networks:
      - microservicesnet

networks:
  microservicesnet:
    driver: bridge